apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  labels:
    app: docker
spec:
  selector:
    matchLabels:
      app: docker
  replicas: 1
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: encrypt
        image: samba1236/sonarqube:kubernetes
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  selector:
    app: docker
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
